### ISSUE TITLE
Error in seg_measure(label, prediction) function

### ISSUE THREAD

**Issue by artaquest** [arbellea/LSTM-UNet#1]
Hi. Thanks for sharing the code.
After following the instruction and fixing some import errors I get an error inside one of the functions. Here's my full terminal output,

(venv) arash@smarta:~/LSTM-UNet-master$ python3 train2D.py 
2019-09-11 15:08:50.341201: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-09-11 15:08:50.365482: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-11 15:08:50.365985: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:01:00.0
2019-09-11 15:08:50.366146: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-09-11 15:08:50.367107: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-09-11 15:08:50.367971: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-09-11 15:08:50.368213: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-09-11 15:08:50.369402: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-09-11 15:08:50.370229: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-09-11 15:08:50.372903: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-09-11 15:08:50.373031: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-11 15:08:50.373589: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-11 15:08:50.374073: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-09-11 15:08:50.374331: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-09-11 15:08:50.396605: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3408000000 Hz
2019-09-11 15:08:50.396843: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4f6a7d0 executing computations on platform Host. Devices:
2019-09-11 15:08:50.396858: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2019-09-11 15:08:50.484207: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-11 15:08:50.484778: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4f6c5f0 executing computations on platform CUDA. Devices:
2019-09-11 15:08:50.484795: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2019-09-11 15:08:50.484930: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-11 15:08:50.485399: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:01:00.0
2019-09-11 15:08:50.485430: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-09-11 15:08:50.485459: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-09-11 15:08:50.485470: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-09-11 15:08:50.485481: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-09-11 15:08:50.485491: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-09-11 15:08:50.485512: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-09-11 15:08:50.485522: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-09-11 15:08:50.485585: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-11 15:08:50.486034: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-11 15:08:50.486458: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-09-11 15:08:50.486481: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-09-11 15:08:50.487190: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-09-11 15:08:50.487200: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-09-11 15:08:50.487205: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-09-11 15:08:50.487276: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-11 15:08:50.487761: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-11 15:08:50.488224: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10311 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
2019-09-11 15:08:50: Reading Sequence ./Fluo-N2DH-SIM+: 01
2019-09-11 15:08:51: Reading Sequence ./Fluo-N2DH-SIM+: 02
2019-09-11 15:08:53: Reading Sequence ./Fluo-N2DH-SIM+: 01
2019-09-11 15:08:54: Reading Sequence ./Fluo-N2DH-SIM+: 02
WARNING:tensorflow:Entity <function CTCRAMReaderSequence2D._create_queues.<locals>.normed_size.<locals>.q_stat at 0x7f9594b941e0> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <function CTCRAMReaderSequence2D._create_queues.<locals>.normed_size.<locals>.q_stat at 0x7f9594b94158> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
2019-09-11 15:08:59: Initializing from scratch.
WARNING:tensorflow:Entity <function train.<locals>.train_step at 0x7f958c1e69d8> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method ULSTMnet2D.call of <Networks.ULSTMnet2D object at 0x7f958c16a550>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method DownBlock2D.call of <Networks.DownBlock2D object at 0x7f958c16a9b0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <function CTCRAMReaderSequence2D._create_queues.<locals>.normed_size.<locals>.q_stat at 0x7f9594b94400> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <function CTCRAMReaderSequence2D._create_queues.<locals>.normed_size.<locals>.q_stat at 0x7f9594b942f0> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method DownBlock2D.call of <Networks.DownBlock2D object at 0x7f958c19f5f8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method DownBlock2D.call of <Networks.DownBlock2D object at 0x7f958c16ac18>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method DownBlock2D.call of <Networks.DownBlock2D object at 0x7f958c19f860>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method UpBlock2D.call of <Networks.UpBlock2D object at 0x7f958c16a978>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method UpBlock2D.call of <Networks.UpBlock2D object at 0x7f958c14cc18>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method UpBlock2D.call of <Networks.UpBlock2D object at 0x7f958c144a20>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method UpBlock2D.call of <Networks.UpBlock2D object at 0x7f958c14ceb8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'
WARNING:tensorflow:From /home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/ops/math_grad.py:1424: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:Entity <bound method SegMeasure.__call__ of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f94943a9f98>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
Traceback (most recent call last):
  File "train2D.py", line 334, in <module>
    train()
  File "train2D.py", line 131, in train
    train_output_sequence, train_predictions, train_loss_value = train_step(image_sequence, seg_sequence)
  File "/home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 427, in __call__
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "/home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 370, in _initialize
    *args, **kwds))
  File "/home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1847, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2147, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2038, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 320, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 905, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: in converted code:

    train2D.py:82 train_step
        seg_value = seg_measure(label, predictions)
    /home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py:427 __call__
        self._initialize(args, kwds, add_initializers_to=initializer_map)
    /home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py:370 _initialize
        *args, **kwds))
    /home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py:1847 _get_concrete_function_internal_garbage_collected
        graph_function, _, _ = self._maybe_define_function(args, kwargs)
    /home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py:2147 _maybe_define_function
        graph_function = self._create_graph_function(args, kwargs)
    /home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py:2038 _create_graph_function
        capture_by_value=self._capture_by_value),
    /home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py:915 func_graph_from_py_func
        func_outputs = python_func(*func_args, **func_kwargs)
    /home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py:320 wrapped_fn
        return weak_wrapped_fn().__wrapped__(*args, **kwds)
    /home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py:2655 bound_method_wrapper
        return wrapped_fn(*args, **kwargs)
    /home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py:902 wrapper
        ), args, kwargs)
    /home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py:534 converted_call
        return _call_unconverted(f, args, kwargs, options)
    /home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py:326 _call_unconverted
        return f.__self__.call(args, kwargs)
    /home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py:2617 call
        return wrapped_fn(self.weakrefself_target__(), *args, **kwargs)
    /home/arash/LSTM-UNet-master/losses.py:60 __call__
        if tf.logical_or(tf.greater(max_label, self.max_labels), tf.less_equal(max_gt_label, 0)):
    /home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:765 __bool__
        self._disallow_bool_casting()
    /home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:531 _disallow_bool_casting
        "using a `tf.Tensor` as a Python `bool`")
    /home/arash/LSTM-UNet-master/venv/local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:518 _disallow_when_autograph_enabled
        " decorating it directly with @tf.function.".format(task))

    OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed: AutoGraph did not convert this function. Try decorating it directly with @tf.function.

**Comment by arbellea** [comment]
Which version of tensorflow are you using?
I'll fix this as soon as possible.
Could you also let me know which import errors you fixed?
Thanks

**Comment by artaquest** [comment]
I installed the dependencies from the requirements.txt file in a python3 virtual environment. So TensorFlow should be version 2 (and I checked, it is '2.0.0-rc0').
I changed the tf.mod() functions to tf.math.mod() and I had to comment this line,
tf.config.gpu.set_per_process_memory_growth(True)
Thank you!

**Comment by arbellea** [comment]
I see that i have the 2.0.0-alpha0 version, and I guess things have changed.
I'll update the code to the rc version as soon as possible and let you know when everything is fixed.
Thanks!

**Comment by artaquest** [comment]
Thanks a million!

**Comment by arbellea** [comment]
I think I fixed all the issues,
However it will take a few days until I'll be back at the lab and will be able to run the full flow,
I updated the repository anyway.
If you like, you could try the updated version and let me know if there are any problems. 
Otherwise, I can let you know when I completely finish debugging.

**Comment by artaquest** [comment]
I tried it now. it failed at installing the TensorFlow. here's the output. Have a nice weekend!

(venv) arash@smarta:~/Downloads/LSTM-UNet-master$ pip3 install -r requirements.txt 
WARNING: The directory '/home/arash/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/arash/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting tensorflow_gpu>=2.0.0a0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/73/cf/2fc69ba3e59edc8333e2676fa71b40197718dea7dc1282c79955cf6b2acb/tensorflow_gpu-2.0.0rc1-cp36-cp36m-manylinux2010_x86_64.whl (380.5MB)
     |████████████████████████████████| 380.5MB 6.7MB/s 
Collecting tensorflow>2.0.0a0 (from -r requirements.txt (line 2))
  ERROR: Could not find a version that satisfies the requirement tensorflow>2.0.0a0 (from -r requirements.txt (line 2)) (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1)
ERROR: No matching distribution found for tensorflow>2.0.0a0 (from -r requirements.txt (line 2))

**Comment by arbellea** [comment]
Fixed the requirements issue and also debugged the rest.
I'm closing this for now, If there are any more problems, please let me know.

**Comment by artaquest** [comment]
Awesome!
Thank you so much
