### ISSUE TITLE
Error copying tensor to device - GoogleColab

### ISSUE THREAD

**Issue by esgomezm** [arbellea/LSTM-UNet#2]
Hi!

I'm trying to run a demo of the training using Google Colaboratory and Fluo-N2DH-GOWT1 dataset but I get the following error below this message. 
The TensorFlow version is 2.0.0-alpha0 and all the parameters are the ones given by default in the code, except for the path. 

Any idea?

Thank you!

```
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using Tensorflow version 2.0.0-alpha0
{}
2020-09-11 15:34:37.700345: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-09-11 15:34:37.716055: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2020-09-11 15:34:37.719056: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-09-11 15:34:37.719123: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:153] kernel driver does not appear to be running on this host (f7a5afe12c68): /proc/driver/nvidia/version does not exist
2020-09-11 15:34:37.722263: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200000000 Hz
2020-09-11 15:34:37.722528: I tensorflow/compiler/xla/service/service.cc:162] XLA service 0x2eb2680 executing computations on platform Host. Devices:
2020-09-11 15:34:37.722619: I tensorflow/compiler/xla/service/service.cc:169]   StreamExecutor device (0): <undefined>, <undefined>
2020-09-11 15:34:37: Reading Sequence /content/dataset/Fluo-N2DH-GOWT1: 01
2020-09-11 15:34:41: Reading Sequence /content/dataset/Fluo-N2DH-GOWT1: 02
2020-09-11 15:34:45: Reading Sequence /content/dataset/Fluo-N2DH-GOWT1: 01
WARNING:tensorflow:Entity <function CTCRAMReaderSequence2D._create_queues.<locals>.normed_size.<locals>.q_stat at 0x7fda3c7fd598> could not be transformed and will be staged without change. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: Unexpected error transforming <function CTCRAMReaderSequence2D._create_queues.<locals>.normed_size.<locals>.q_stat at 0x7fda3c7fd598>. If you believe this is due to a bug, please set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output when filing the bug report. Caused by: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <function CTCRAMReaderSequence2D._create_queues.<locals>.normed_size.<locals>.q_stat at 0x7fda3c7fd510> could not be transformed and will be staged without change. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: Unexpected error transforming <function CTCRAMReaderSequence2D._create_queues.<locals>.normed_size.<locals>.q_stat at 0x7fda3c7fd510>. If you believe this is due to a bug, please set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output when filing the bug report. Caused by: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <function CTCRAMReaderSequence2D._create_queues.<locals>.normed_size.<locals>.q_stat at 0x7fda3c7fd6a8> could not be transformed and will be staged without change. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: Unexpected error transforming <function CTCRAMReaderSequence2D._create_queues.<locals>.normed_size.<locals>.q_stat at 0x7fda3c7fd6a8>. If you believe this is due to a bug, please set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output when filing the bug report. Caused by: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <function CTCRAMReaderSequence2D._create_queues.<locals>.normed_size.<locals>.q_stat at 0x7fda3c7fd7b8> could not be transformed and will be staged without change. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: Unexpected error transforming <function CTCRAMReaderSequence2D._create_queues.<locals>.normed_size.<locals>.q_stat at 0x7fda3c7fd7b8>. If you believe this is due to a bug, please set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output when filing the bug report. Caused by: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <function CTCRAMReaderSequence2D._create_queues.<locals>.normed_size.<locals>.q_stat at 0x7fda3c7fd8c8> could not be transformed and will be staged without change. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: Unexpected error transforming <function CTCRAMReaderSequence2D._create_queues.<locals>.normed_size.<locals>.q_stat at 0x7fda3c7fd8c8>. If you believe this is due to a bug, please set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output when filing the bug report. Caused by: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <function CTCRAMReaderSequence2D._create_queues.<locals>.normed_size.<locals>.q_stat at 0x7fda3c7fd8c8> could not be transformed and will be staged without change. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: Unexpected error transforming <function CTCRAMReaderSequence2D._create_queues.<locals>.normed_size.<locals>.q_stat at 0x7fda3c7fd8c8>. If you believe this is due to a bug, please set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output when filing the bug report. Caused by: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <function CTCRAMReaderSequence2D._create_queues.<locals>.normed_size.<locals>.q_stat at 0x7fda3c7fd7b8> could not be transformed and will be staged without change. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: Unexpected error transforming <function CTCRAMReaderSequence2D._create_queues.<locals>.normed_size.<locals>.q_stat at 0x7fda3c7fd7b8>. If you believe this is due to a bug, please set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output when filing the bug report. Caused by: Bad argument number for Name: 3, expecting 4
2020-09-11 15:35:02: Reading Sequence /content/dataset/Fluo-N2DH-GOWT1: 02
Traceback (most recent call last):
  File "/content/LSTM-UNet/train2D.py", line 365, in <module>
    train()
  File "/content/LSTM-UNet/train2D.py", line 52, in train
    train_loss = k.metrics.Mean(name='train_loss')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/metrics.py", line 428, in __init__
    reduction=metrics_utils.Reduction.WEIGHTED_MEAN, name=name, dtype=dtype)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/metrics.py", line 270, in __init__
    'total', initializer=init_ops.zeros_initializer)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/metrics.py", line 251, in add_weight
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 377, in add_weight
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/base.py", line 622, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 152, in make_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py", line 212, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py", line 175, in _variable_v1_call
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py", line 154, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 2492, in default_variable_creator
    import_scope=import_scope, distribute_strategy=distribute_strategy)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py", line 216, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 422, in __init__
    constraint=constraint)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 545, in _init_from_args
    initial_value() if init_from_fn else initial_value,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 134, in <lambda>
    init_val = lambda: initializer(shape, dtype=dtype)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py", line 115, in __call__
    return array_ops.zeros(shape, dtype)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py", line 1826, in zeros
    output = _constant_if_small(zero, shape, dtype, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py", line 1784, in _constant_if_small
    return constant(value, shape=shape, dtype=dtype, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py", line 245, in constant
    allow_broadcast=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py", line 253, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py", line 110, in convert_to_eager_tensor
    t = ops.EagerTensor(value, handle, device, dtype)
RuntimeError: Error copying tensor to device: /job:localhost/replica:0/task:0/device:GPU:0. /job:localhost/replica:0/task:0/device:GPU:0 unknown device.
```

**Comment by arbellea** [comment]
Hi, 
Which machine are you running on?
Which GPUs do you have? How many?

**Comment by arbellea** [comment]
From the comments here:https://stackoverflow.com/questions/49624596/using-a-gpu-with-tensorflow-eager-execution-on-google-colaboratory
It seems that there is some bug in google colaboratory...
