### ISSUE TITLE
I am facing error:    TypeError: object of type 'NoneType' has no len(). please help. And why Groundtruth data image are just black image without any masks?

### ISSUE THREAD

**Issue by imran7778** [arbellea/LSTM-UNet#3]
I am training the model using dataset available http://celltrackingchallenge.net/2d-datasets/ . After downloading all celltracking data, I have seen that each dataset have just black images in Groundtruth folder. For example;  in folder **Fluo-C2DL-Huh7** =>**01_GT** => **SEG** and **TRA** both folder have all black images, what kind of groundtruth is this? I don't understand. 

However, On this data I have make the _metadata_01.pickle_ and _metadata_02.pickle_ using _create_sequence_metadata.py_.
Then I have run the _train2D.py_ but getting the following error. I am runing this code on google colab.

!python train2D.py

2021-07-16 13:42:35.999027: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Using Tensorflow version 2.5.0
{}
2021-07-16 13:42:37.538368: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-07-16 13:42:37.567422: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-16 13:42:37.568054: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2021-07-16 13:42:37.568112: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-16 13:42:37.571044: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-07-16 13:42:37.571125: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2021-07-16 13:42:37.572879: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2021-07-16 13:42:37.573238: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2021-07-16 13:42:37.573478: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2021-07-16 13:42:37.574087: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2021-07-16 13:42:37.574283: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-07-16 13:42:37.574311: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-07-16 13:42:37.574694: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-07-16 13:42:37.574838: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-07-16 13:42:37.574862: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      
2021-07-16 13:42:37: Reading Sequence /content/drive/MyDrive/Colab Notebooks/LSTM/coding/LSTM-UNet/Training/Fluo-C2DL-Huh7: 01
2021-07-16 13:42:38: Reading Sequence /content/drive/MyDrive/Colab Notebooks/LSTM/coding/LSTM-UNet/Training/Fluo-C2DL-Huh7: 02
Traceback (most recent call last):
  File "train2D.py", line 365, in <module>
    train()
  File "train2D.py", line 41, in train
    train_data_provider.start_queues(coord)
  File "/content/drive/My Drive/Colab Notebooks/LSTM/coding/LSTM-UNet/DataHandeling.py", line 502, in start_queues
    self._read_sequence_to_ram_()
  File "/content/drive/My Drive/Colab Notebooks/LSTM/coding/LSTM-UNet/DataHandeling.py", line 90, in _read_sequence_to_ram_
    if len(img_size) == 3:
TypeError: object of type 'NoneType' has no len()

**Comment by imran7778** [comment]
One of my issue has been resolved related to [TypeError: object of type 'NoneType' has no len()] because my folder **02** was empty.

Now i just need to know why all images in folder 02_GT and 01_GT are black, without any type of masks of the cells in those images?

**Comment by aarbelle** [comment]
I am glad you managed to solve the error. 
The images are most likely not black, but since they are uint16 with small numbers they seem black. 
If you try opening the images in python/matlab and checking the values of the pixels you will most likely see they are not all 0.

**Comment by aarbelle** [comment]
@imran7778 
Did you manage to see the images? 
Can I close the issue?
Thanks

**Comment by imran7778** [comment]
@aarbelle thanks for your reply, I have seen it in Matlab, yes these images are not black there are some values in the mask images. You can close thanks.
